language: c

os:
    - linux
    - osx

env:
    matrix:
        - PYTHON_VERSION=2.7 PSUTIL_VERSION=1
        - PYTHON_VERSION=2.7 PSUTIL_VERSION=2
        - PYTHON_VERSION=3.3 PSUTIL_VERSION=3
        - PYTHON_VERSION=3.4 PSUTIL_VERSION=4
        - PYTHON_VERSION=3.5 PSUTIL_VERSION=5
        - PYTHON_VERSION=3.6 PSUTIL_VERSION=5
    global:
        - CONDA_DEPENDENCIES='matplotlib psutil'
        - PIP_DEPENDENCIES='coveralls pytest-cov'
        - SETUP_XVFB=True

before_install:
    # Make sure we can get the version without any dependencies installed
    - python setup.py --version
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
    - py.test --cov psrecord psrecord
    - python setup.py check --restructuredtext
    - pip install flake8
    - flake8 psrecord

after_success:
    - coveralls
